name: .NET CI

on:
  pull_request: 
    branches:
      - main
        
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Install dependecies
        run: dotnet restore PracticeGamestore.sln
        
      - name: Build solution
        run: dotnet build PracticeGamestore.sln --no-restore -c Release
        
      - name: Run tests
        run: dotnet test PracticeGamestore.Tests/PracticeGamestore.csproj --no-build -c Release